name: Build & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout 
      uses: actions/checkout@v3.3.0
      
    
    - name: Install Node.js
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 16.x
    
    - name: Install NPM packages
      run: npm ci
    
    - name: Build project
      run: npm run build

    - name: Upload production-ready build files
      uses: actions/upload-pages-artifact@v1.0.7
      with:
        name: production-files
        path: build/
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.2.4
      with:
        artifact_name: production-files
